[build]
  base = "modules/leitor-editais"
  publish = ".next"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  SKIP_ENV_VALIDATION = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
